// Mocks generated by Mockito 5.4.4 from annotations
// in restaurant_app/test/history_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant_app/core/failure/failure.dart' as _i6;
import 'package:restaurant_app/features/history/domain/entity/history_entity.dart'
    as _i7;
import 'package:restaurant_app/features/history/domain/repository/history_repository.dart'
    as _i2;
import 'package:restaurant_app/features/history/domain/usecases/history_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIHistoryRepository_0 extends _i1.SmartFake
    implements _i2.IHistoryRepository {
  _FakeIHistoryRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryUseCase extends _i1.Mock implements _i4.HistoryUseCase {
  MockHistoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IHistoryRepository get historyRepository => (super.noSuchMethod(
        Invocation.getter(#historyRepository),
        returnValue: _FakeIHistoryRepository_0(
          this,
          Invocation.getter(#historyRepository),
        ),
      ) as _i2.IHistoryRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.HistoryEntity>>> getHistory(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [page],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.HistoryEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.HistoryEntity>>(
          this,
          Invocation.method(
            #getHistory,
            [page],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.HistoryEntity>>>);
}
